-
    version: 1.0.0.{build}-{branch}
    branches:
      only:
        - master
    configuration: Release
    before_build:
      - appveyor-retry dotnet restore -v Normal
    build:
      publish_nuget: true
      verbosity: minimal

-
    version: 1.0.0.{build}-{branch}
    branches:
      only:
        - vNext
    configuration: Release
    before_build:
      - appveyor-retry dotnet restore -v Normal
    build:
      publish_nuget: false
      verbosity: minimal